### ISSUE TITLE
off topic / magento saml

### ISSUE THREAD

**Issue by f1-outsourcing** [procinger/turing-pi-v2-cluster#139]
Hi @procinger  Adam,

I hope you do not mind me writing you here. I wanted to use with OpenMage[1] your saml plugin. Do you think you can revive this? Currently it breaks my shop. I am willing to pay for this, I can also prepare dev environment so you can have quick look.

[1]
https://github.com/OpenMage/magento-lts

**Comment by procinger** [comment]
Hi @f1-outsourcing ,

unfortunately, you will have to find a freelancer to make the necessary adjustments, sorry.

When this module was developed, I was very active in the Magento/PHP scene. That was so many years ago now that I don't even know what has changed since PHP 5 or what OpenMage is.

I know that this is not what you wanted to hear, but I keep my fingers crossed that you find someone who can help you with your problem :crossed_fingers:
